# Correct the OR, merge files by phenotype, select significant associations. Configuration: U-shape.

#################################################
### Libraries & External arguments ##############
library(data.table)
library(dplyr)
library(tibble)
library(gtools)

# Arguments
args <- commandArgs(trailingOnly = T)
sex <- args[1]
print(paste0("Analyzing: ", sex))

# Filter for probe selection
thr <- 0.05/6633 # = 7.5e-6



#################################################
### STEP 1: Correct ORs #########################

# List all files to correct; Generated by "05_gwas/04_gwas/01_binary_gwas_U_*.sh"
files_to_correct <- list.files(paste0("/cauwerx/gwas/05_gwas/04_gwas/u_shape/data/temp/", sex), pattern = "*.glm.*", recursive = F, full.names = T)
print(paste0("Number of files to analyze: ", length(files_to_correct)))

# Loop over files to correct
for (f in files_to_correct) {

	# Load file
	df <- as.data.frame(fread(f, header = T))

	#### Continuous trait (DiseaseBurden) ####
	if (grepl("DiseaseBurden", f))  {

		# Make relevant columns numeric
		df[9:14] <- lapply(df[9:14], as.numeric)

		# Correct all associations (effect of being copy neutral --> effect of having a CNV)
		df[, c(9, 11, 12, 13)] <- -1 * df[, c(9, 11, 12, 13)]
		colnames(df)[c(11,12)] <- c("U95", "L95")
		df <- df[, c(1:10, 12, 11, 13:15)]

	#### Binary traits (others) ##############
	} else {

		# Make relevant columns numeric
		df[10:15] <- lapply(df[10:15], as.numeric)

		# Correct all associations (effect of being copy neutral --> effect of having a CNV)
		df[, "OR"] <- exp(-log(df[, "OR"]))
		df[, "L95"] <- exp(log(df[, "OR"]) - 1.96*df[, "LOG(OR)_SE"]) 
		df[, "U95"] <- exp(log(df[, "OR"]) + 1.96*df[, "LOG(OR)_SE"]) 
		df[, "Z_STAT"] <- log(df[, "OR"])/df[, "LOG(OR)_SE"]
	}

	# Save
	fwrite(df, f, col.names = T, row.names = F, sep = "\t", quote = F)

}



#################################################
### STEP 2: Merge by phenotype ##################

# List unique diseases; Header of the file generated by "04_phenotypes/01_ICD10_extraction.R"
all_pheno <- c(names(as.data.frame(fread(paste0("/cauwerx/gwas/04_phenotypes/data/pheno_ICD10_", sex,".txt"), nrow = 0)))[-1])

# Create an empty dataframe to store results
significant_associations <- data.frame() 

# Loop over diseases
for (p in all_pheno) {

	# Define disease
	print(paste0("Analyzing: ", p, " (u-shape, ", sex,")"))

	# List files corresponding to the defined phenotype
	files_p <- mixedsort(list.files(paste0("/cauwerx/gwas/05_gwas/04_gwas/u_shape/data/temp/", sex), pattern = paste0("*\\.", p, ".glm"), recursive = F, full.names = T))
	print(paste0("Number of files to merge: ", length(files_p)))

	# Merge all listed files
	df <- data.frame()
	for (fp in files_p) {
		df_temp <- as.data.frame(fread(fp, header = T))
		df <- rbind(df, df_temp)
	}

	# If DiseaseBurden, add an additional column for compatibility
	if(p == "DiseaseBurden") {
		df <- add_column(df, `FIRTH?` = NA, .before = "TEST")
		colnames(df)[c(10,11,14)] <- c("OR", "LOG(OR)_SE", "Z_STAT")}

	# Save
	fwrite(df, paste0("/cauwerx/gwas/05_gwas/04_gwas/u_shape/data/", sex,"/gwas_U_", sex,".", p, ".txt"), col.names = T, row.names = F, sep = "\t", quote = F)

	# Retain significant files & Save
	sig_df <- df[df$P <= thr & !is.na(df$P), ]
	print(paste0("Number of significant associations: ", nrow(sig_df)))
	if (nrow(sig_df) > 0) {
		fwrite(sig_df, paste0("/cauwerx/gwas/05_gwas/04_gwas/u_shape/data/", sex,"/significant/gwas_significant_U_", sex,".", p, ".txt"), col.names = T, row.names = F, sep = "\t", quote = F)}

	# If there is at least one significant association, combine with global dataframe
	if (nrow(sig_df) > 0) {
		sig_df$PHENO <- p
		significant_associations <- rbind(significant_associations, sig_df)}
	
}


#################################################
### Save significant associations ###############

# Order and save
significant_associations <- significant_associations[mixedorder(significant_associations$`#CHROM`, significant_associations$POS, significant_associations$PHENO, decreasing = F), ]
fwrite(significant_associations, paste0("/cauwerx/gwas/05_gwas/04_gwas/u_shape/data/", sex,"/significant/00_significant_U_", sex,".txt"), col.names = T, row.names = F, sep = "\t", quote = F)
