#!/bin/bash

#################
#   RUN INFO    #
#################

#SBATCH --job-name=probe_selection      # Give your job a name to recognize it in queue overview
#SBATCH --nodes=1          		 		# Define number of nodes required
#SBATCH --time=0-02:00:00        		# Define how long the job will run (max. is 7 days, default is 1h)
#SBATCH --mem=5GB           	 		# Memory required per node
#SBATCH --cpus-per-task=20

# Parallelize by chromosome
#SBATCH --array=1-24
#SBATCH --output=/cauwerx/gwas/05_gwas/03_probe_selection/data/log/01_probe_selection_M-%A_%a.out


#################
#   VARIABLES   #
#################

echo "SLURM_JOB_ID: " $SLURM_JOB_ID
echo "SLURM_ARRAY_ID: " $SLURM_ARRAY_ID
echo "SLURM_ARRAY_TASK_ID: " $SLURM_ARRAY_TASK_ID

#################
#   JOB INFO    #
#################

chromosomes=$(echo 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 XY X)
chr=$(echo ${chromosomes} | cut -f ${SLURM_ARRAY_TASK_ID} -d ' ')

##################
#    RUN JOB     #
##################

## DEFINE VARIABLES #######################

# PLINK file set with mirror encoding; Generation of this file is described in Auwerx et al., 2022 
input=$(echo "/data/UKBB/cnv_calls/PLINK/mirror/ukb_cnv_bed/ukb_cnv_chr${chr}")

# Disease diagnosis; File generated by "04_phenotypes/01_ICD10_extraction.R"
pheno_M=$(echo "/cauwerx/gwas/04_phenotypes/data/pheno_ICD10_M_plink_v1.9.txt")

# Samples: white-british individuals; Generated by "01_samples/sample_filtering.R"
samples_M=$(echo "/cauwerx/gwas/01_samples/data/samples_white_british_plink1.9_M.txt")

# Probes (pruned); Generated by "02_probes/01_freq_prune.R"
probes=$(echo "/cauwerx/gwas/02_probes/data/pruning/probes_WB_All_prune_0.9999_CNV_chr${chr}.prune.in")

# Output
output_M=$(echo "/cauwerx/gwas/05_gwas/03_probe_selection/data/temp/M/probe_effect_Fisher_M_chr${chr}")


## RUN PLINK - M #########################

/cauwerx/softwares/plink/plink  --threads 20 \
								--bfile ${input} \
								--fam /data/UKBB/cnv_calls/PLINK/mirror/ukb_cnv_bed/ukb_cnv_chrX_onlyF.fam \ # Fake .fam file (all individuals = females) to deal with PLINK's male hemizygozity assumption (see Supplemental Note 1)
						        --keep ${samples_M} \
						        --extract ${probes} \
                                --pheno ${pheno_M} --all-pheno \
								--model fisher \
								--out ${output_M}
wait

echo "Done"
