# Select phenotype-specific covariates (p < 0.05)

##################################################
### Libraries & External arguments ###############
library(data.table)
library(dplyr)

# Arguments
args <- commandArgs(trailingOnly = T)
sex <- args[1]
print(paste0("Analyzing: ", sex))



#################################################
### Load data ###################################

# Load disease data; File generated by "04_phenotypes/01_ICD10_extraction.R"
pheno <- as.data.frame(fread(paste0("/cauwerx/gwas/04_phenotypes/data/pheno_ICD10_", sex,".txt")))

# Load covariate data (age, sex, array, PC1-PC40) and retain selected individuals (in pheno file); File generated by "03_covariates/01_covariate_extraction.R"
cov <- as.data.frame(fread("/cauwerx/gwas/03_covariates/data/covariates.txt",select = c(1,2,4,5,7:46)))
cov <- cov[cov$IID %in% pheno$IID, ]



#################################################
### STEP 1: Logistic regression #################

# Significance threshold for covariate selection
thr <- 0.05

# Create an empty file to save the summary of all phenotypes
summary <- data.frame(DISEASE = names(pheno)[-1], COV = NA)

# Loop over diseases, perform a logistic regression, and retain significant covariates
for (p in names(pheno)[-1]) {

	print(paste0("Analyzing: ", p))

	# Create a temporary dataframe with no missing data
	df <- na.omit(left_join(pheno[, names(pheno) %in% c("IID", p)], cov, by = "IID"))[, -1]
	colnames(df)[1] <- "DISEASE"

	# Regression
	if(p == "DiseaseBurden") {
			# Linear regression (continuous trait, i.e., disease burden)
			df$DISEASE <- as.numeric(df$DISEASE)
			fit <- lm(DISEASE ~ . , data = df)
	} else {
			# Logistic regression (binary trait)
			df$DISEASE <- factor(df$DISEASE, levels = c(1,2), labels = c(0, 1))
			fit <- glm(DISEASE ~ . , data = df, family = binomial(link = "logit"))
	}

	# Select significant covariates
	fit_p <- summary(fit)$coef[-1,4]
	selected_cov <- names(fit_p[fit_p <= thr])
	print(paste0("Number of retained covariates: ", length(selected_cov)))

	# Collapse for further usage by PLINK, Save
	selected_cov <- gsub("arrayUKBL", "array", selected_cov)
	selected_cov  <- data.frame(COV = paste(selected_cov , collapse = ","))
	fwrite(selected_cov , paste0("/cauwerx/gwas/05_gwas/02_covariate_selection/data/", sex,"/covariates_", sex,".", p, ".txt"), row.names = F, col.names = F, sep = "\t", quote = F)

	# Add to meta-file
	summary[summary$DISEASE == p, "COV"] <- as.character(selected_cov[1,1])

}


#################################################
### Save data ###################################

fwrite(summary, paste0("/cauwerx/gwas/05_gwas/02_covariate_selection/data/summary_covariates_", sex,".txt"), row.names = F, col.names = T, sep = "\t", quote = F)
