# Detect associations between the CNV burden (measured in number of genes or Mb) and the ICD10-based disease burden (linear regression).

#################################################
### Libraries & External arguments ##############
library(data.table)
library(dplyr)

# Arguments
args <- commandArgs(trailingOnly = T)
b <- args[1]
print(paste0("Analyzing: ", b))



#################################################
### STEP 1: Load data ###########################

# Disease burden data; Files generated by "04_phenotypes/01_ICD10_extraction.R"
phenotype <- as.data.frame(fread("/cauwerx/gwas/04_phenotypes/data/pheno_ICD10_All.txt", header = T, select = c(1,58)))

# CNV burden data; Files generated as in Auwerx et al., 2022 (scripts: "Burden_analysis/CNV_burden/*_burden_calculation.R")
burdens <- as.data.frame(fread(paste0("data/UKBB/CNV_burden/", b, "_burden.txt.gz"), header = T, select = c(1,4,10)))

# Covariates - Subset the relevant covariates
covariates <- as.data.frame(fread("/cauwerx/gwas/03_covariates/data/covariates.txt")) # File generated by "03_covariates/01_covariate_extraction.R"
selected_cov <- as.data.frame(fread(paste0("/cauwerx/gwas/05_gwas/02_covariate_selection/data/All/covariates_All.DiseaseBurden.txt"), header = F, sep = "\t")) # file generated by "05_gwas/02_covariate_selection/01_covariate_selection.R"
print(paste0("Selected covariates: ", selected_cov))
selected_cov <- unlist(strsplit(selected_cov[1,1],","))
selected_cov <- covariates[, names(covariates) %in% c("IID", selected_cov)]



#################################################
### STEP 2: Regression analysis #################

# Merge relevant dataframes
df <- na.omit(left_join(phenotype, burdens, by = "IID"))
df <- na.omit(left_join(df, selected_cov, by = "IID"))

# Create an empty dataframe to store the results
results <- data.frame(PHENO = rep("DiseaseBurden", 2), BURDEN = c("Mb", "GENES"),TYPE = rep("linear", 2))

# Linear regression: DiseaseBurden ~ BURDEN_Mb + Covariates 
fit_linear_Mb <- lm(DiseaseBurden ~ ., data = df[-c(1,4)])
results[1, "N"] <- nrow(df)
results[1, "BETA"] <- summary(fit_linear_Mb)$coef[2,1]
results[1, "SE"] <- summary(fit_linear_Mb)$coef[2,2]
results[1, "T"] <- summary(fit_linear_Mb)$coef[2,3]
results[1, "P"] <- summary(fit_linear_Mb)$coef[2,4]

# Linear regression: DiseaseBurden ~ BURDEN_GENES + Covariates
fit_linear_GENES <- lm(DiseaseBurden ~ ., data = df[-c(1,3)])
results[2, "N"] <- nrow(df)
results[2, "BETA"] <- summary(fit_linear_GENES)$coef[2,1]
results[2, "SE"] <- summary(fit_linear_GENES)$coef[2,2]
results[2, "T"] <- summary(fit_linear_GENES)$coef[2,3]
results[2, "P"] <- summary(fit_linear_GENES)$coef[2,4]


#################################################
### Save results ################################

fwrite(results, paste0("/cauwerx/gwas/09_burden_analysis/data/no_CNVR_correction/", b, "_burden_analysis_DiseaseBurden.txt"), col.names = T, row.names  = F, quote = F, sep = "\t")
