# Detect associations between the CNV burden (measured in number of genes or Mb) and ICD10-based diagnoses (logistic regression).

#################################################
### Libraries & External arguments ##############
library(data.table)
library(dplyr)

# Arguments
args <- commandArgs(trailingOnly = T)
b <- args[1]
print(paste0("Analyzing: ", b))



#################################################
### STEP 1: Load data ###########################

# Phenotype data (inc. sex-specific); Files generated by "04_phenotypes/01_ICD10_extraction.R"
phenotypes <- as.data.frame(fread("/cauwerx/gwas/04_phenotypes/data/pheno_ICD10_All.txt", header = T, select = c(1:57)))
phenotypes_M <- as.data.frame(fread("/cauwerx/gwas/04_phenotypes/data/pheno_ICD10_M.txt", header = T, select = c(1,4)))
phenotypes <- left_join(phenotypes, phenotypes_M, by = "IID"); rm(phenotypes_M)
phenotypes_F <- as.data.frame(fread("/cauwerx/gwas/04_phenotypes/data/pheno_ICD10_F.txt", header = T, select = c(1:3,60:61)))
phenotypes <- left_join(phenotypes, phenotypes_F, by = "IID"); rm(phenotypes_F)

# CNV burden data; Files generated as in Auwerx et al., 2022 (scripts: "Burden_analysis/CNV_burden/*_burden_calculation.R")
burdens <- as.data.frame(fread(paste0("data/UKBB/CNV_burden/", b, "_burden.txt.gz"), header = T, select = c(1,4,10)))

# Covariates: File generated by "03_covariates/01_covariate_extraction.R"
covariates <- as.data.frame(fread("/cauwerx/gwas/03_covariates/data/covariates.txt"))



#################################################
### STEP 2: Loop over diseases ##################

# Create an empty dataframe to store the results
results <- data.frame(PHENO = rep(names(phenotypes)[!names(phenotypes) %in% c("IID")], each = 2),
							 BURDEN = rep(c("Mb", "GENES"), times = ncol(phenotypes)-1),
							 TYPE = "logistic",
							 Y_X = "Disease_Burden&Cov")
count <- 1

# Loop over diseases
for(p in names(phenotypes)[-1]) {

	# Define disease & sex
	print(paste0("Testing for association between ", p, " and CNV burden"))
	sex <- "All"
	if (p %in% c("PC")) {sex <- "M"}
	if (p %in% c("BC", "OC", "menstruation", "endometriosis")) {sex <- "F"}

	# Identify relevant covariates: Load phenotype-specific selected covariates (generated by "05_gwas/02_covariate_selection/01_covariate_selection.R"), if there is at least one, otherwise retain IID only; 
	if (file.size(paste0("/cauwerx/gwas/05_gwas/02_covariate_selection/data/", sex, "/covariates_", sex, ".", p,".txt")) > 1) {
			selected_cov <- as.data.frame(fread(paste0("/cauwerx/gwas/05_gwas/02_covariate_selection/data/", sex, "/covariates_", sex, ".", p,".txt"), header = F, sep = "\t"))
			print(paste0("Selected covariates: ", selected_cov))
			selected_cov <- unlist(strsplit(selected_cov[1,1],","))
			selected_cov <- covariates[, names(covariates) %in% c("IID", selected_cov)]
	} else {
			print("Selected covariates: /")
			selected_cov <- covariates[, names(covariates) %in% c("IID"), drop = F]
	}

	# Define a temporary dataframe & clean it
	df <- na.omit(left_join(phenotypes[, names(phenotypes) %in% c("IID", p)], burdens, by = "IID"))
	df <- na.omit(left_join(df, selected_cov, by = "IID"))
	colnames(df)[2] <- "PHENO" 
	df$PHENO <- factor(df$PHENO, levels = c(1,2), labels = c(0,1))
	 
	# Logistic regression: Disease ~ BURDEN_Mb + Covariates
	fit_logistic_Mb <- glm(PHENO ~ . , data = df[-c(1,4)], family = binomial(link = "logit")) 
	results[count, "N"] <- nrow(df)
	results[count, "BETA"] <- summary(fit_logistic_Mb)$coef[2,1]
	results[count, "OR"] <- exp(summary(fit_logistic_Mb)$coef[2,1])
	results[count, "SE"] <- summary(fit_logistic_Mb)$coef[2,2]
	results[count, "Z"] <- summary(fit_logistic_Mb)$coef[2,3]
	results[count, "P"] <- summary(fit_logistic_Mb)$coef[2,4]
	count <- count + 1

	# Logistic regression: Disease ~ BURDEN_GENES + Covariates
	fit_logistic_GENES <- glm(PHENO ~ . , data = df[-c(1,3)], family = binomial(link = "logit")) 
	results[count, "N"] <- nrow(df)
	results[count, "BETA"] <- summary(fit_logistic_GENES)$coef[2,1]
	results[count, "OR"] <- exp(summary(fit_logistic_GENES)$coef[2,1])
	results[count, "SE"] <- summary(fit_logistic_GENES)$coef[2,2]
	results[count, "Z"] <- summary(fit_logistic_GENES)$coef[2,3]
	results[count, "P"] <- summary(fit_logistic_GENES)$coef[2,4]
	count <- count + 1
}


#################################################
### Save results ################################

fwrite(results, paste0("/cauwerx/gwas/09_burden_analysis/data/no_CNVR_correction/", b, "_burden_analysis_binary.txt"), col.names = T, row.names  = F, quote = F, sep = "\t")
