# Disease burden association with CNV burden - WITH correction for CNV-GWAS (linear regression).

#################################################
### Libraries & External arguments ##############
library(data.table)
library(dplyr)
library(tidyr)
library(stringr)

# Arguments
args <- commandArgs(trailingOnly = T)
b <- args[1]
print(paste0("Analyzing: ", b))

# Define relevant models based on b
if (b == "CNV") {
	model <- paste(c("M","U"), collapse = "|")
} else {
	model <- tolower(b)
}



#################################################
### STEP 1: Correct the phenotype ###############

# Disease burden data; Files generated by "04_phenotypes/01_ICD10_extraction.R"
phenotype <- as.data.frame(fread("/cauwerx/gwas/04_phenotypes/data/pheno_ICD10_All.txt", header = T, select = c(1,58)))


# Covariates - Subset the relevant covariates
covariates <- as.data.frame(fread("/cauwerx/gwas/03_covariates/data/covariates.txt")) # File generated by "03_covariates/01_covariate_extraction.R"
cov_reg <- as.data.frame(fread(paste0("/cauwerx/gwas/05_gwas/02_covariate_selection/data/All/covariates_All.DiseaseBurden.txt"), header = F, sep = "\t")) # file generated by "05_gwas/02_covariate_selection/01_covariate_selection.R"
print(paste0("Selected regular covariates: ", cov_reg))
cov_reg <- unlist(strsplit(cov_reg[1,1],","))
cov_reg <- covariates[, names(covariates) %in% c("IID", cov_reg)]
print(paste0("Number of samples with regular covariates: ", nrow(cov_reg)))


# Load and retain CNVRs associated with the DiseaseBurden (--> select the appropriated model); File generated by "07_CNVR/combined/01_combine_models.R"
cnvr <- as.data.table(fread("/cauwerx/gwas/07_CNVR/combined/data/combined_CNVR/all_combined_CNVR.txt", header = T, select = c(3,8,9,1,11), col.names = c("CHR", "START", "END", "PHENO", "MODELS")))
cnvr <- cnvr[which(cnvr$PHENO == "DiseaseBurden"), ]					#  Select associations with the DiseaseBurden
cnvr$MODELS <- gsub("DUP", "dup", cnvr$MODELS) 
cnvr$MODELS <- gsub("DEL", "del", cnvr$MODELS) 
cnvr <- cnvr[grep(model, cnvr$MODELS), ]								# Retain CNVs associating under a particular model
cnvr <- cnvr[which(cnvr$CHR != "X"), c(1:4)] 							# Retain autosomal CNVs
cnvr$CHR <- as.numeric(cnvr$CHR)
cnvr$ID <- paste0("chr", cnvr$CHR, "_", cnvr$START, "_", cnvr$END)		# Add unique ID
print(paste0("Number of unique autosomal CNVRs (", model, ") : ", nrow(cnvr)))
if (nrow(cnvr) == 0) {stop("No associated CNVRs --> Stop execution")}



#################################################
### STEP 2: Correct the CNV burden #############

# Load & retain high confidence autosomal CNVs ; Files generated as in Auwerx et al., 2022 (i.e., final output of the PennCNV/QS pipeline) 
cnvs <- as.data.table(fread("/data/UKBB/cnv_calls/PenCNV/ukb_cnv_global.gz", header = T, select = c(1:5, 18), col.names = c("IID", "CHR", "START", "END", "CN", "QS")))
cnvs$IID <- as.numeric(sub("_.*", "", cnvs$IID))
cnvs <- cnvs[!cnvs$CHR %in% c(23, 24), ]							# Retain autosomal CNVs
cnvs <- cnvs[which(abs(cnvs$QS) >= 0.5), ] 							# Filter for quality score
if(model == "dup") {cnvs <- cnvs[which(cnvs$CN > 2), ]}				# Retain duplications for the DUP burden analysis
if(model == "del") {cnvs <- cnvs[which(cnvs$CN < 2), ]}				# Retain deletions for the DEL burden analysis
print(paste0("Number of retained autosomal CNVs: ", nrow(cnvs)))

# Overlap between CNVs and CNVRs
setkey(cnvr, CHR, START, END)										# Set key		
overlap <- na.omit(as.data.frame(foverlaps(cnvs, cnvr, maxgap = 0L, minoverlap = 1L, type = "any", mult = "all"))); rm(cnvs)
overlap <- overlap[, c(5:9)] 
overlap <- overlap[!duplicated(overlap), ] 							# e.i., Pleiotropic CVVs
print(paste0("Number of overlaps: ", nrow(overlap)))

# CNV burden data; Files generated as in Auwerx et al., 2022 (scripts: "Burden_analysis/CNV_burden/*_burden_calculation.R")
cnv_burden <- as.data.frame(fread(paste0("data/UKBB/CNV_burden/", b, "_burden.txt.gz"), header = T, select = c(1,4,10)))
print(paste0("Number of samples with CNV burden: ", nrow(cnv_burden)))



#### Mb #########################################

# Correct the Mb burden (substract the length of disease-associated CNVR overlapping CNVs)
df_mb <- overlap[overlap$ID %in% cnvr$ID, ]										# Identify relevant CNVs
print(paste0("Number of overlapping CNVs with covariate CNVRs: ", nrow(df_mb)))
df_mb$LENGTH_Mb <- ((df_mb$i.END - df_mb$i.START) + 1)/1000000					# Calculate the length of relevant CNVs
df_mb <- aggregate(LENGTH_Mb ~ IID, df_mb, sum)									# Calculate the aggregate length of relevant CNVs
cnv_burden <- left_join(cnv_burden, df_mb, by = "IID")							# Merge aggregated length of relevant CNVs to burden information 
cnv_burden[is.na(cnv_burden$LENGTH_Mb), "LENGTH_Mb"] <- 0
cnv_burden$BURDEN_Mb_corrected <- cnv_burden$BURDEN_Mb - cnv_burden$LENGTH_Mb	# Substract aggregated length of relevant CNVs from the burden



#### Genes ######################################

# Correct the GENES burden (substract the number of HGNC genes of disease-associated CNVR overlapping CNVs)
df_gene <- overlap[overlap$ID %in% cnvr$ID, ]									# Identify relevant CNVs

# Run ANNOVAR (HGNC)
df_gene <- data.frame(CHR = sub("_.*", "", sub("chr", "", df_gene$ID)), START = df_gene$i.START, END  = df_gene$i.END, REF = 0, OBS = "-", IID = df_gene$IID)
input <- paste0("/cauwerx/gwas/09_burden_analysis/data/temp/ANNOVAR/", b, "_DiseaseBurden_ANNOVAR_input.txt")
output <- paste0("/cauwerx/gwas/09_burden_analysis/binary/white_british/data/temp/ANNOVAR/", b,"_DiseaseBurden_ANNOVAR_output")
fwrite(df_gene, input, col.names = F, row.names = F, quote = F, sep = "\t")
system(paste("/cauwerx/softwares/ANNOVAR-20191024/annotate_variation.pl",
			 "--geneanno -dbtype refGene",
			 "-out", output, 
			 "-build hg19", 
			 input,
			 "/cauwerx/softwares/ANNOVAR-20191024/humandb/"))	
unlink(paste0(output, ".log"))

# Load annotated CNVs and retain the ones overlapping coding sequences
df_gene <- as.data.frame(fread(paste0(output, ".variant_function"), header = F, select = c(1,2,8), col.names = c("REGION", "GENE", "IID"))); rm(output, input)
print(paste0("Number of annotated CNVs: ", nrow(df_gene)))
df_gene <- df_gene[grep(paste(c("exonic", "splicing", "ncRNA", "UTR5", "UTR3"), collapse = "|"), df_gene$REGION), ]
print(paste0("Remaining CNVs after filtering for gene impact (stringent): ", nrow(df_gene)))

# Calculate a corrected burden
df_gene <- aggregate(GENE ~ IID, df_gene[, c("IID", "GENE")], paste, collapse = ",")
df_gene$LENGTH_GENES <- as.numeric(lapply(lapply(strsplit(df_gene$GENE, ","), unique), length)) # Identify the number of unique gene overlapping disease-associated CNVRs
cnv_burden <- left_join(cnv_burden, df_gene[, c(1,3)], by = "IID")								# Merge aggregated length of relevant CNVs to burden information
cnv_burden[is.na(cnv_burden$LENGTH_GENES), "LENGTH_GENES"] <- 0
cnv_burden$BURDEN_GENES_corrected <- cnv_burden$BURDEN_GENES - cnv_burden$LENGTH_GENES			# Substract the number of gene overlapping relevant CNVs from the burden
	
# Merge corrected burdens
cnv_burden <- cnv_burden[,names(cnv_burden) %in% c("IID", "BURDEN_Mb_corrected", "BURDEN_GENES_corrected")]
rm(df_mb, df_gene)



#################################################
### STEP 3: CNVR corrected burden analysis ######

# Create an dataframe to store results
results <- data.frame(PHENO = rep("DiseaseBurden", 2), BURDEN = c("Mb", "GENES"), TYPE = rep("linear", 2), Y_vs_X = rep("Disease_Cov_CNVR_vs_Burden", 2), Corrected_Burden = rep("Yes", 2))

# Merge relevant dataframe
df <- na.omit(left_join(phenotype, cnv_burden, by = "IID"))	
df <- na.omit(left_join(df, cov_reg, by = "IID"))	
print(paste0("Number of individuals analyzed: ", nrow(df)))	

# Linear regression analysis: DiseaseBurden_correctedINT ~ BURDEN_Mb_corrected
fit_linear_Mb <- lm(DiseaseBurden ~ ., data = df[, !names(df) %in% c("IID", "BURDEN_GENES_corrected")])
results[1, "N"] <- nrow(df)
results[1, "BETA"] <- summary(fit_linear_Mb)$coef[2,1]
results[1, "SE"] <- summary(fit_linear_Mb)$coef[2,2]
results[1, "T"] <- summary(fit_linear_Mb)$coef[2,3]
results[1, "P"] <- summary(fit_linear_Mb)$coef[2,4]

# Linear regression analysis: DiseaseBurden_correctedINT ~ BURDEN_GENES_corrected
fit_linear_GENES <- lm(DiseaseBurden ~ ., data = df[, !names(df) %in% c("IID", "BURDEN_Mb_corrected")])
results[2, "N"] <- nrow(df)
results[2, "BETA"] <- summary(fit_linear_GENES)$coef[2,1]
results[2, "SE"] <- summary(fit_linear_GENES)$coef[2,2]
results[2, "T"] <- summary(fit_linear_GENES)$coef[2,3]
results[2, "P"] <- summary(fit_linear_GENES)$coef[2,4]


#################################################
### Save results ################################

fwrite(results, paste0("/cauwerx/gwas/09_burden_analysis/data/CNVR_correction/", b, "_burden_analysis_CNVR_correction_DiseaseBurden.txt"), col.names = T, row.names  = F, quote = F, sep = "\t")
