# Disease association with CNV burden - WITH correction for CNV-GWAS (logistic regression).

#################################################
### Libraries & External arguments ##############
library(data.table)
library(dplyr)
library(tidyr)
library(stringr)

# Arguments
args <- commandArgs(trailingOnly = T)
b <- args[1]
print(paste0("Analyzing: ", b))

# Define relevant models based on b
if (b == "CNV") {
	model <- paste(c("M","U"), collapse = "|")
} else {
	model <- tolower(b)
}



#################################################
### STEP 1: Load data ###########################

# Phenotype data (inc. sex-specific); Files generated by "04_phenotypes/01_ICD10_extraction.R"
phenotypes <- as.data.frame(fread("/cauwerx/gwas/04_phenotypes/data/pheno_ICD10_All.txt", header = T, select = c(1:57)))
phenotypes_M <- as.data.frame(fread("/cauwerx/gwas/04_phenotypes/data/pheno_ICD10_M.txt", header = T, select = c(1,4)))
phenotypes <- left_join(phenotypes, phenotypes_M, by = "IID"); rm(phenotypes_M)
phenotypes_F <- as.data.frame(fread("/cauwerx/gwas/04_phenotypes/data/pheno_ICD10_F.txt", header = T, select = c(1:3,60:61)))
phenotypes <- left_join(phenotypes, phenotypes_F, by = "IID"); rm(phenotypes_F)
print(paste0("Number of phenotype: ", ncol(phenotypes)-1))

# CNV burden data; Files generated as in Auwerx et al., 2022 (scripts: "Burden_analysis/CNV_burden/*_burden_calculation.R")
burdens <- as.data.frame(fread(paste0("data/UKBB/CNV_burden/", b, "_burden.txt.gz"), header = T, select = c(1,4,10)))
print(paste0("Number of samples with CNV burden: ", nrow(cnv_burden)))

# Covariates: File generated by "03_covariates/01_covariate_extraction.R"
covariates <- as.data.frame(fread("/cauwerx/gwas/03_covariates/data/covariates.txt"))
print(paste0("Number of samples with regular covariates: ", nrow(covariates)))

# All CNV regions to analyze (--> select appropriated model); File generated by "07_CNVR/combined/01_combine_models.R"
cnvr <- as.data.table(fread("/cauwerx/gwas/07_CNVR/combined/data/combined_CNVR/all_combined_CNVR.txt", header = T, select = c(3,8,9,1,11), col.names = c("CHR", "START", "END", "PHENO", "MODELS")))
cnvr$MODELS <- gsub("DUP", "dup", cnvr$MODELS) 
cnvr$MODELS <- gsub("DEL", "del", cnvr$MODELS) 
cnvr <- cnvr[grep(model, cnvr$MODELS), ]							# Retain CNVs associating under a particular model
cnvr <- cnvr[which(cnvr$CHR != "X"), c(1:4)] 						# Retain autosomal CNVs
cnvr$CHR <- as.numeric(cnvr$CHR)
cnvr$ID <- paste0("chr", cnvr$CHR, "_", cnvr$START, "_", cnvr$END)	# Add unique ID
print(paste0("Number of unique autosomal CNVRs (", model, ") : ", nrow(cnvr)))

# Load all CNVs and retain high confidence autosomal CNVs; Files generated as in Auwerx et al., 2022 (i.e., final output of the PennCNV/QS pipeline) 
cnvs <- as.data.table(fread("/data/UKBB/cnv_calls/PenCNV/ukb_cnv_global.gz", header = T, select = c(1:5, 18), col.names = c("IID", "CHR", "START", "END", "CN", "QS")))
cnvs$IID <- sub("_.*", "", cnvs$IID)
cnvs$IID <- as.numeric(cnvs$IID)
cnvs <- cnvs[!cnvs$CHR %in% c(23, 24), ]							# Retain autosomal CNVs
cnvs <- cnvs[which(abs(cnvs$QS) >= 0.5), ] 							# Filter for quality score
if(model == "dup") {cnvs <- cnvs[which(cnvs$CN > 2), ]}				# Retain duplications for the DUP burden analysis
if(model == "del") {cnvs <- cnvs[which(cnvs$CN < 2), ]}				# Retain deletions for the DEL burden analysis
print(paste0("Number of retained autosomal CNVs: ", nrow(cnvs)))



#################################################
### STEP 2: Overlap CNVs with CNVRs #############

# Set  key
setkey(cnvr, CHR, START, END)

# Overlap between CNVs and CNVRs
overlap <- na.omit(as.data.frame(foverlaps(cnvs, cnvr, maxgap = 0L, minoverlap = 1L, type = "any", mult = "all")))
overlap <- overlap[, c(5:9)] 
overlap <- overlap[!duplicated(overlap), ] 								# e.i., Pleiotropic CVVs
print(paste0("Number of overlaps: ", nrow(overlap)))
rm(cnvs)



#################################################
### STEP 3: CNVR corrected burden analysis ######

# Create an empty dataframe to store results
results <- data.frame(PHENO = rep(names(phenotypes)[-1], each = 2), BURDEN = rep(c("Mb", "GENES"), times = ncol(phenotypes)-1), TYPE = "logistic", Y_vs_X = "Disease_vs_BurdenCorrected_Cov", CNVR = "No")
count <- 1

# Regions considered for gene annotation
regions <- c("exonic", "splicing", "ncRNA", "UTR5", "UTR3")

# Loop over diseases
for(p in names(phenotypes)[-1]) {

	######################################
	### Define disease & sex #############
	print(paste0("Testing for association between ", p, " and CNV burden"))
	sex <- "All"
	if (p %in% c("PC")) {sex <- "M"}
	if (p %in% c("BC", "OC", "menstruation", "endometriosis")) {sex <- "F"}


	######################################
	### Identify relevant covariates ##### 

	# Load phenotype-specific selected covariates (generated by "05_gwas/02_covariate_selection/01_covariate_selection.R"), if there is at least one, otherwise retain IID only
	if (file.size(paste0("/cauwerx/gwas/05_gwas/02_covariate_selection/data/", sex, "/covariates_", sex, ".", p,".txt")) > 1) {
			cov_reg <- as.data.frame(fread(paste0("/cauwerx/gwas/05_gwas/02_covariate_selection/data/", sex, "/covariates_", sex, ".", p,".txt"), header = F, sep = "\t"))
			print(paste0("Selected regular covariates: ", cov_reg))
			cov_reg <- unlist(strsplit(cov_reg[1,1],","))
			cov_reg <- covariates[, names(covariates) %in% c("IID", cov_reg)]
	} else {
			print("Selected regular covariates: /")
			cov_reg <- covariates[, names(covariates) %in% c("IID"), drop = F]
	}


	######################################
	### Correct the burden ############### 

	df_burden <- cnv_burden

	if (nrow(cnvr[which(cnvr$PHENO == p), ]) > 0) { 

			print("CNVR covariates --> Correct the CNV burdens")

			# Correct the Mb burden (Substract the length of disease-associated CNVR overlapping CNVs)
			df_mb <- overlap[overlap$ID %in% cnvr[which(cnvr$PHENO == p), "ID"]$ID, ]		# Identify relevant CNVs
			print(paste0("Number of overlapping CNVs with covariate CNVRs: ", nrow(df_mb)))
			df_mb$LENGTH_Mb <- ((df_mb$i.END - df_mb$i.START) + 1)/1000000					# Calculate the length of relevant CNVs
			df_mb <- aggregate(LENGTH_Mb ~ IID, df_mb, sum)									# Calculate the aggregate length of relevant CNVs
			df_burden <- left_join(df_burden, df_mb, by = "IID")							# Merge aggregated length of relevant CNVs to burden information 
			df_burden[is.na(df_burden$LENGTH_Mb), "LENGTH_Mb"] <- 0
			df_burden$BURDEN_Mb_corrected <- df_burden$BURDEN_Mb - df_burden$LENGTH_Mb		# Substract aggregated length of relevant CNVs from the burden


			# Correct the GENES burden (Substract the number of HGNC genes of disease-associated CNVR overlapping CNVs)
			df_gene <- overlap[overlap$ID %in% cnvr[which(cnvr$PHENO == p), "ID"]$ID, ]		# Identify relevant CNVs

				# Run ANNOVAR (HGNC)
				df_gene <- data.frame(CHR = sub("_.*", "", sub("chr", "", df_gene$ID)), START = df_gene$i.START, END  = df_gene$i.END, REF = 0, OBS = "-", IID = df_gene$IID)
				input <- paste0("/cauwerx/gwas/09_burden_analysis/data/temp/ANNOVAR/", b, "_", p,"_ANNOVAR_input.txt")
				output <- paste0("/cauwerx/gwas/09_burden_analysis/data/temp/ANNOVAR/", b,"_", p,"_ANNOVAR_output")
				fwrite(df_gene, input, col.names = F, row.names = F, quote = F, sep = "\t")
				system(paste("/cauwerx/softwares/ANNOVAR-20191024/annotate_variation.pl",
							 "--geneanno -dbtype refGene",
							 "-out", output, 
							 "-build hg19", 
							 input,
							 "/cauwerx/softwares/ANNOVAR-20191024/humandb/"))	
				unlink(paste0(output, ".log"))

			df_gene <- as.data.frame(fread(paste0(output, ".variant_function"), header = F, select = c(1,2,8), col.names = c("REGION", "GENE", "IID"))); rm(output, input)
			print(paste0("Number of annotated CNVs: ", nrow(df_gene)))
			df_gene <- df_gene[grep(paste(regions, collapse = "|"), df_gene$REGION), ]
			print(paste0("Remaining CNVs after filtering for gene impact (stringent): ", nrow(df_gene)))

			df_gene <- aggregate(GENE ~ IID, df_gene[, c("IID", "GENE")], paste, collapse = ",")
			df_gene$LENGTH_GENES <- as.numeric(lapply(lapply(strsplit(df_gene$GENE, ","), unique), length)) # Identify the number of unique gene overlapping disease-associated CNVRs
			df_burden <- left_join(df_burden, df_gene[, c(1,3)], by = "IID")								# Merge aggregated length of relevant CNVs to burden information
			df_burden[is.na(df_burden$LENGTH_GENES), "LENGTH_GENES"] <- 0
			df_burden$BURDEN_GENES_corrected <- df_burden$BURDEN_GENES - df_burden$LENGTH_GENES				# Substract the number of gene overlapping relevant CNVs from the burden
			
			# Clean
			df_burden <- df_burden[,names(df_burden) %in% c("IID", "BURDEN_Mb_corrected", "BURDEN_GENES_corrected")]
			rm(df_mb, df_gene)

	} else {
			print("No CNVR covariates --> Do not correct the CNV burdens")
			colnames(df_burden) <- c("IID", "BURDEN_Mb_corrected", "BURDEN_GENES_corrected")
	}


	######################################
	### Merge relevant dataframes ######## 

	df <- na.omit(left_join(phenotypes[, names(phenotypes) %in% c("IID", p)], df_burden, by = "IID"))	
	df <- na.omit(left_join(df, cov_reg, by = "IID"))
	colnames(df)[2] <- "PHENO" 
	df$PHENO <- factor(df$PHENO, levels = c(1,2), labels = c(0,1))
	print(paste0("Number of individuals analyzed: ", nrow(df)))	
	rm(df_burden, cov_reg)


	######################################
	### Regression analysis ############## 

	# Logistic regression: Disease ~ BURDEN_Mb_corrected + Covariates
	fit_logistic_Mb <- glm(PHENO ~ . , data = df[, !names(df) %in% c("IID", "BURDEN_GENES_corrected")], family = binomial(link = "logit"))
	results[count, "N"] <- nrow(df)
	results[count, "BETA"] <- summary(fit_logistic_Mb)$coef[2,1]
	results[count, "OR"] <- exp(summary(fit_logistic_Mb)$coef[2,1])
	results[count, "SE"] <- summary(fit_logistic_Mb)$coef[2,2]
	results[count, "Z"] <- summary(fit_logistic_Mb)$coef[2,3]
	results[count, "P"] <- summary(fit_logistic_Mb)$coef[2,4]
	count <- count + 1

	# Logistic regression: Disease ~ BURDEN_GENES_corrected + Covariates
	fit_logistic_GENES <- glm(PHENO ~ . , data = df[, !names(df) %in% c("IID", "BURDEN_Mb_corrected")], family = binomial(link = "logit"))
	results[count, "N"] <- nrow(df)
	results[count, "BETA"] <- summary(fit_logistic_GENES)$coef[2,1]
	results[count, "OR"] <- exp(summary(fit_logistic_GENES)$coef[2,1])
	results[count, "SE"] <- summary(fit_logistic_GENES)$coef[2,2]
	results[count, "Z"] <- summary(fit_logistic_GENES)$coef[2,3]
	results[count, "P"] <- summary(fit_logistic_GENES)$coef[2,4]
	count <- count + 1

}



#################################################
### STEP 4: Detect significant associations #####

#  Calculate threshold (55 diseases + 1 male-specific + 4 female-specific + 1 DiseaseBurden)
thr <- 0.05/61

# Print output
print(paste0("There are ", nrow(results[which(results[ , 11] <= thr), ])," significant associations across ", length(unique(results[which(results[ , 11] <= thr), "PHENO"]))," phenotypes"))



#################################################
### Save results ################################

fwrite(results, paste0("/cauwerx/gwas/09_burden_analysis/data/CNVR_correction/", b, "_burden_analysis_CNVR_correction_binary.txt"), col.names = T, row.names  = F, quote = F, sep = "\t")
