# Prune significant probes from the CNV-GWAS. Configuration: U-shape model.

#################################################
### Libraries & External arguments ##############
library(data.table)
library(dplyr)
library(scales)

#Arguments
args <- commandArgs(trailingOnly = T)
sex <- args[1]
print(paste0("Analyzing: ", sex))



#################################################
### STEP 1: List file ###########################

# Load significant GWAS data; File generated by "05_gwas/04_gwas/u_shape/02_correct_merge_binary_gwas_U.R" 
sig_probes <- as.data.frame(fread(paste0("/cauwerx/gwas/05_gwas/04_gwas/u_shape/data/", sex, "/significant/00_significant_U_", sex, ".txt")))
sig_probes <- sig_probes[, c(17, 1:3, 15)]
colnames(sig_probes)[2] <-  "CHR"



#################################################
### STEP 2: Prune ###############################

# Unique combinations of disease - chromosome pairs
unique_combo <- as.data.frame(sig_probes %>% count(PHENO, CHR))
colnames(unique_combo)[3] <- "TOTAL"

# Parameters
window <- 3000000
r2 <- 0.8

# Empty dataframe to store results
summary_pruning <- unique_combo

# Loop over files to prune
for (i in 1:nrow(unique_combo)){

	# Define disease and chromosome & select probes
	p <- unique_combo[i, "PHENO"]
	chr <- unique_combo[i, "CHR"]
	df <- sig_probes[which(sig_probes$PHENO == p & sig_probes$CHR == chr), ]
	print(paste0("Pruning chromosome ", chr, " for ", p, " (", nrow(df), " probe(s))"))

	# File names
	result_file <- paste0("/cauwerx/gwas/05_gwas/05_pruning/u_shape/data/temp/", sex, "/probes_U_", sex, "_r2_", r2, "_chr", chr, ".", p)
	probe_file <- paste0("/cauwerx/gwas/05_gwas/05_pruning/u_shape/data/temp/", sex, "/probes/input_probes_U_", sex, "_chr", chr,".", p, ".txt")

	# If there is only one probe, retain and save it for the next step
	if(nrow(df) == 1){

		# Save the probe
		print("Number of remaining after pruning: 1")
		fwrite(df[, "ID", drop = F], paste0(result_file, ".prune.in"), col.names = F, row.names = F, quote = F, sep = "\t")

		# Fill in the summary table
		summary_pruning[i, "PRUNED"] <- 1

		# Go to the next loop iteration
		next
	
	
	# Else, prune probes (manually)
	}  else {

		# Prepare a probe file
		fwrite(df[, "ID", drop = F], probe_file, row.names = F, col.names = F, sep = "\t", quote = F)

		# Extract probes from the PLINK file
		input <- paste0("/data/UKBB/cnv_calls/PLINK/mirror/ukb_cnv_bed/ukb_cnv_chr", chr) # PLINK file set with mirror encoding; Generation of this file is described in Auwerx et al., 2022
		samples <- paste0("/cauwerx/gwas/01_samples/data/samples_white_british_plink1.9_", sex, ".txt") # File generated by "01_samples/sample_filtering.R"
		system(paste("/cauwerx/softwares/plink/plink",
					 "--fam /data/UKBB/cnv_calls/PLINK/mirror/ukb_cnv_bed/ukb_cnv_chrX_onlyF.fam", # Fake .fam file (all individuals = females) to deal with PLINK's male hemizygozity assumption (see Supplemental Note 1) 
					 "--threads 20",
					 "--bfile", input, 
					 "--keep", samples, 
					 "--extract", probe_file,
					 "--recode tab --out", result_file))

		# Load and correct the .ped in R; Make all columns numerical; Delete the PLINK files
	 	ped <- as.data.frame(fread(paste0(result_file, ".ped"), header = F, select = c(2,7:(6+nrow(df))), col.names = c("IID", df$ID)))
		ped[ped == "A A" | ped == "T T"] <- 1
		ped[ped == "A T" | ped == "T A"] <- 0
		for (j in 2:ncol(ped)) {ped[, j] <- as.numeric(ped[, j])}
		unlink(paste0(result_file, ".log")); unlink(paste0(result_file, ".map")); unlink(paste0(result_file, ".ped"))

		# Calculate the squared probe correlation matrix
		r2_matrix <- cor(ped[, -1])^2
		rm(ped)

		# Order probes in df according to position; While loop to analyze multiple loci within the same chromosome
		to_analyze <- df[order(df$POS), ]
		prune_in <- vector()
		while(nrow(to_analyze) > 0) {

			# Select the first probe and those +3Mb; Remove them from the probes to be analyzed
			first_probe_POS <- to_analyze[1, "POS"]
			probes_3Mb <- to_analyze[which(to_analyze$POS >= first_probe_POS & to_analyze$POS <= first_probe_POS + window),  ]
			to_analyze <- to_analyze[!to_analyze$ID %in% probes_3Mb$ID, ]

			# Wile loop to retain uncorrelated probes
			while(nrow(probes_3Mb) > 0) {

				# Select the most significant probe within the region and add it to the prune_in vector
				top_probe_ID <- probes_3Mb[which.min(probes_3Mb$P), "ID"]
				prune_in <- c(prune_in, top_probe_ID)

				# Identify correlated probes; Remove them from the probes_3Mb matrix
				corr_to_top_probe <- rownames(r2_matrix[which(r2_matrix[, top_probe_ID] >= r2), , drop = F])
				probes_3Mb <- probes_3Mb[!probes_3Mb$ID %in% corr_to_top_probe, ]
			}
		}

			# Output the number of retained probes and save
			print(paste0("Number of remaining after pruning: ", length(prune_in)))
			fwrite(data.frame(ID = prune_in), paste0(result_file, ".prune.in"), col.names = F, row.names = F, quote = F, sep = "\t")

			# Fill in the summary table
			summary_pruning[i, "PRUNED"] <- length(prune_in)
		}
} 
rm(i, p, chr, df, result_file, probe_file, input, samples, r2_matrix, to_analyze, prune_in, first_probe_POS, probes_3Mb, top_probe_ID, corr_to_top_probe)


# Print a summary & save
print(paste("pruning at r2 =", r2, " reduced the number of probes from ", sum(summary_pruning$TOTAL), " to ", sum(summary_pruning$PRUNED)))	
fwrite(summary_pruning, paste0("/cauwerx/gwas/05_gwas/05_pruning/u_shape/data/", sex, "/00_summary_pruning_U_", sex, ".txt"), row.names = F, col.names = T, quote = F, sep = "\t") 



#################################################
### STEP 3: Extract remaining probes ############

# Identify unique diseases with at least one probe
unique_p <- unique(summary_pruning$PHENO)
print(paste0(length(unique_p)," phenotypes to assess"))

# Create an empty dataframe to store summary of the quality control
summary_qc <- data.frame()

# Loop over remaining diseases and extract association informationfor these probes
for (up in unique_p){

	# List relevant prune.in files
	prune.in_list <- list.files(path = paste0("/cauwerx/gwas/05_gwas/05_pruning/u_shape/data/temp/", sex), pattern = paste0("\\.", up, ".prune.in"), full.names = T, recursive = F)

 	# Load and merge relevant prune.in files
	df_probes <- data.frame()
	for (f in prune.in_list) {
		df <- as.data.frame(fread(f, header = F, col.names = "ID"))
		df_probes <- rbind(df_probes, df)	
	}; rm(f, df)
	print(paste0("Retaining ", nrow(df_probes), " probe(s) for ", up))

	# Load relevant GWAS association data; File generated by "05_gwas/04_gwas/u_shape/02_correct_merge_binary_gwas_U.R" 
	df_gwas <- as.data.frame(fread(paste0("/cauwerx/gwas/05_gwas/04_gwas/u_shape/data/", sex, "/significant/gwas_significant_U_", sex, ".", up, ".txt")))

	# Subset retained probes
	df_gwas_probes <- df_gwas[df_gwas$ID %in% df_probes$ID, ]
	if (nrow(df_probes) != nrow(df_gwas_probes)){print("Warning! Number of retained probes does not match.")} 

	# Save retained probes/phenotype for the SCA
	fwrite(data.frame(ID = df_gwas_probes$ID), paste0("/cauwerx/gwas/05_gwas/05_pruning/u_shape/data/", sex, "/SCA_probes/qc_probes_U_", sex, ".", up, ".txt"), col.names = F, row.names = F, quote = F, sep = "\t")

	# Add results to the main summary QC file
	df_gwas_probes$PHENO <- up
	summary_qc <- rbind(summary_qc, df_gwas_probes)

}



#################################################
### Save input for SCA ##########################

# Save GWAS summary statistics for the stepwise conditional analysis (first round) 
fwrite(summary_qc, paste0("/cauwerx/gwas/05_gwas/05_pruning/u_shape/data/", sex, "/00_qc_probes_gwas_U_", sex, ".txt"), col.names = T, row.names = F, quote = F, sep = "\t")

