# Batch effect on disease status --> Conclusion: only the array seems to have an effect

##################################################
### Libraries & External arguments ###############
library(data.table)
library(dplyr)

# Arguments
args <- commandArgs(trailingOnly = T)
sex <- args[1]
print(paste0("Analyzing: ", sex))



#################################################
### Load data ###################################

# Load disease data; File generated by "04_phenotypes/01_ICD10_extraction.R"
pheno <- as.data.frame(fread(paste0("/cauwerx/gwas/04_phenotypes/data/pheno_ICD10_", sex,".txt"), header = T))

# Load covariate data (batches); File generated by "03_covariates/01_covariate_extraction.R"
cov <- as.data.frame(fread("/cauwerx/gwas/03_covariates/data/covariates.txt",select = c(1,6)))
cov <- cov[cov$IID %in% pheno$IID, ]
cov$batch <- gsub("Batch_", "", cov$batch)



#################################################
### STEP 1: Logistic regression #################

# Define significance threshold for covariate selection
thr <- 0.05/length(unique(cov$batch))

# Create an empty file to save the summary results of all diseases
summary <- data.frame(DISEASE = names(pheno)[-1], BATCH = NA)

# Loop over diseases, perform a logistic regression, and retain significant covariates (i.e., batches)
for (p in names(pheno)[-1]) {

	print(paste0("Analyzing: ", p, " (", sex,")"))

	# Create a temporary dataframe with no missing data
	df <- na.omit(left_join(pheno[, names(pheno) %in% c("IID", p)], cov, by = "IID"))[, -1]
	colnames(df)[1] <- "DISEASE"

	# Regression
	if(p == "DiseaseBurden") {
			# Linear regression (continuous trait, i.e., disease burden)
			df$DISEASE <- as.numeric(df$DISEASE)
			fit <- lm(DISEASE ~ . , data = df)
	} else {
			# Logistic regression (binary trait)
			df$DISEASE <- factor(df$DISEASE, levels = c(1,2), labels = c(0, 1))
			fit <- glm(DISEASE ~ . , data = df, family = binomial(link = "logit"))
	}

	# Select significant batches
	fit_p <- summary(fit)$coef[-1,4]
	selected_batch <- names(fit_p[fit_p <= thr])
	selected_batch <- gsub("batch", "", selected_batch)
	print(paste0("Number of retained batches: ", length(selected_batch)))
	selected_batch  <- data.frame(BATCH = paste(selected_batch , collapse = ","))

	# Add to meta-file
	summary[summary$DISEASE == p, "BATCH"] <- as.character(selected_batch[1,1])

}



#################################################
### Save data ###################################

fwrite(summary, paste0("/cauwerx/gwas/05_gwas/01_batch_effect/data/summary_batch_effect_", sex,".txt"), row.names = F, col.names = T, sep = "\t", quote = F)
