# Extract phenotype information for CKD and generate a PLINK-compatible file

#################################################
### Libraries ###################################
library(data.table)
library(dplyr)
library(tidyr)
library(stringr)
library(tibble)



#################################################
### Load Main Data ##############################

# Phenotype list; Contains the definition of inclusion and exclusion lists for CKD with and without exclusion of people with related conditions
pheno_list <- as.data.frame(fread("/data/phenotypes/ICD10_CKD.txt", header = T))



#################################################
### STEP 1: Select relevant phenotype columns ###

# Self-reported data: cancer (SRC) and other diseases (SRD); "ukb44073.csv" contains phenotypic data for field 20001 (self-reported cancer; SRC) and 20002 (self-reported disease; SRD) available from the UKBB portal (downloaded: 10/2020)
header <- as.data.frame(fread("/data/UKBB/pheno/ukb44073.csv", header = T, nrow = 0))
col_SRC <- grep("^20001-", names(header))
col_SRD <- grep("^20002-", names(header))
rm(header)

# File downloaded in 05/2022 (ukb52238.csv)
header <- as.data.frame(fread("/data/UKBB/pheno/ukb52238.csv", header = T, nrow = 0))
col_ICD <- grep("^41270-", names(header))
rm(header)



#################################################
### STEP 2: Generate index tables ###############
# That is a table with all the disease codes received by each individual in a long format; one per UKBB field 

# Self-reported cancer (#20001)
SRC <- as.data.frame(fread("/data/UKBB/pheno/ukb44073.csv", header = T, select = c(1, col_SRC), colClass = "character"))
SRC[SRC==""] <- NA
SRC <- na.omit(gather(SRC, Instance, Code, 2:ncol(SRC)))
SRC <- unique(SRC[, c(1,3)])

# Self-reported disease (#20002)
SRD <- as.data.frame(fread("/data/UKBB/pheno/ukb44073.csv", header = T, select = c(1, col_SRD), colClass = "character"))
SRD[SRD==""] <- NA
SRD <- na.omit(gather(SRD, Instance, Code, 2:ncol(SRD)))
SRD <- unique(SRD[, c(1,3)])

# ICD10 diagnosis (#41270)
ICD <- as.data.frame(fread("/data/UKBB/pheno/ukb52238.csv", header = T, select = c(1, col_ICD), colClass = "character"))
ICD[ICD==""] <- NA
ICD <- na.omit(gather(ICD, Instance, Code, 2:ncol(ICD)))
ICD <- unique(ICD[, c(1,3)])



#################################################
### STEP 3: Generate phenotype tables ###########
# That is a table with all the disease diagnoses as per our definition, combining information from the different fields (samples x diseases)

# Load white-british individuals; Generated by "01_samples/sample_filtering.R"
eid_all <- as.data.frame(fread("/cauwerx/gwas/01_samples/data/samples_white_british_All.txt", header = F, col.names = "eid"))

# Generate an empty table, where every individual is a control (i.e., 1)
pheno_all <- as.data.frame(matrix(data = 1, nrow = nrow(eid_all), ncol = nrow(pheno_list), dimnames = list(c(1:nrow(eid_all)), c(pheno_list$phenotype))))
pheno_all <- cbind(eid_all, pheno_all)


### 3.1 Exclusion list ###########################
# Set individuals with a code/diagnosis on the exclusion list to missing (i.e., NA)

# Loop over diseases
for (p in 1:nrow(pheno_list)) {

	# Define disease
	pheno <- pheno_list[p, "phenotype"]
	print(paste0("Starting to exclude individuals for ", pheno))

	# Excluded SRC (#20001)
	excl_SRC <- str_split(pheno_list[p, "exclude_20001"], ", ")[[1]]
	excl_SRC_eid <- unique(SRC[SRC$Code %in% excl_SRC, "eid"])

	# Excluded SRD (#20002)
	excl_SRD <- str_split(pheno_list[p, "exclude_20002"], ", ")[[1]]
	excl_SRD_eid <- unique(SRD[SRD$Code %in% excl_SRD, "eid"])

	# Excluded ICD (#41270)
	excl_ICD <- str_split(pheno_list[p, "exclude_41270"], ", ")[[1]]
	excl_ICD <- paste(paste0(sub("\\.", "", excl_ICD), ".*"), collapse = "|")
	excl_ICD_eid <- ICD %>% filter(str_detect(Code, excl_ICD))
	excl_ICD_eid <- unique(excl_ICD_eid$eid)

	# Merged exclusion list
	excl <- as.numeric(unique(c(excl_SRC_eid, excl_SRD_eid, excl_ICD_eid)))
	print(paste0("Number of individuals excluded for ", pheno, ": ", length(excl)))
	
	# Correct the table
	pheno_all[pheno_all$eid %in% excl, pheno] <- NA

}


### 3.2 Inclusion list ##########################
# Set individuals with a code on the inclusion list to cases (i.e., 2)

# Loop over diseases
for (p in 1:nrow(pheno_list)) {

	# Define disease
	pheno <- pheno_list[p, "phenotype"]
	print(paste0("Starting to include individuals for ", pheno))

	# Include ICD (#41270)
	incl_ICD <- str_split(pheno_list[p, "include_41270"], ", ")[[1]]
	incl_ICD <- paste(paste0(sub("\\.", "", incl_ICD), ".*"), collapse = "|")
	incl_ICD_eid <- ICD %>% filter(str_detect(Code, incl_ICD))
	incl_ICD_eid <- as.numeric(unique(incl_ICD_eid$eid))
	print(paste0("Number of individuals included for ", pheno, ": ", length(incl_ICD_eid)))
	
	# Correct the table
	pheno_all[pheno_all$eid %in% incl_ICD_eid, pheno] <- 2

}

colnames(pheno_all)[1] <- "IID"
print(paste0("Dimensions of disease table for unrelated white British samples: ", ncol(pheno_all)-1, " pheno x ", nrow(pheno_all), " individuals"))



#################################################
### Save results ################################

fwrite(pheno_all, "/cauwerx/gwas/10_candidates/17q12/data/pheno/CKD_ICD10_All.txt", col.names = T, row.names = F, quote = F, sep = "\t", na = "NA")
