# Verify if associations are robust using an alternative modelling strategy (post-hoc 2x3 Fisher test (genotypic)).

#################################################
### Libraries ###################################
library(data.table)
library(dplyr)



#################################################
### STEP 1: Load CNVRs ##########################

# All CNV regions to analyze (remove those with the disease burden); File generated by "07_CNVR/combined/01_combine_models.R"
cnvrs <- as.data.frame(fread("/cauwerx/gwas/07_CNVR/combined/data/combined_CNVR/all_combined_CNVR.txt", header = F, select = c(1:11), col.names = c("PHENO", "TOP_SNP", "CHR", "POS", "OR", "SE", "P", "START_CNVR", "END_CNVR", "MAIN_MODEL", "ALL_MODELS")))
cnvrs <- cnvrs[!cnvrs$PHENO %in% c("DiseaseBurden"), ]
print(paste0("Number of associations to analyze: ", nrow(cnvrs)))

# Load all probes; This file contains the rs ID and position of all probes on the genotype array, available from the UKBB portal
probes <- as.data.frame(fread("/data/general_data/UKBB/probes.txt.gz"))



#################################################
### STEP 2: Loop over CNVRs #####################

# Loop over associations
for (i in 1:nrow(cnvrs)) {

	# Define the association
	pheno <- as.character(cnvrs[i, "PHENO"])
	rs <- as.character(cnvrs[i, "TOP_SNP"])
	sex <- "All"; if(pheno %in% c("BC", "OC", "menstruation", "endometriosis")) {sex <- "F"}; if(pheno %in% c("PC")) {sex <- "M"}
	chr <- as.character(cnvrs[i, "CHR"]); if (chr == "X") {if(probes[which(probes$SNP == rs), "Chr"] == "23") {chr <- "XY"}}
	print(paste0("Analyzing association #", i, ": ", rs, " & ", pheno))

	# Load the appropriated Fisher test file and extract; File generated by "05_gwas/03_probe_selection/01_get_probe_effect_All.sh" 
	fisher <- as.data.frame(fread(paste0("/cauwerx/gwas/05_gwas/03_probe_selection/data/temp/", sex,"/probe_effect_Fisher_", sex, "_chr", chr,".", pheno, ".model"), header = T))
	cnvrs[i, "P_FISHER"] <- as.numeric(fisher[which(fisher$SNP == rs & fisher$TEST == "GENO"), "P"])

}



#################################################
### Save results ################################

fwrite(cnvrs, "/cauwerx/gwas/07_CNVR/combined/data/Fisher/posthoc_Fisher_cnvrs.txt", col.names = T, row.names = F, quote = F, sep = "\t")
