# Prune significant probes from the CNV-GWAS. Configuration: Duplication-only model.

#################################################
### Libraries & External arguments ##############
library(data.table)
library(dplyr)
library(scales)

# Arguments
args <- commandArgs(trailingOnly = T)
sex <- args[1]
print(paste0("Analyzing: ", sex))



#################################################
### STEP 1: List files ##########################

# Load significant GWAS data; File generated by "05_gwas/04_gwas/duplication_only/02_correct_merge_binary_gwas_dup.R" 
sig_probes <- as.data.frame(fread(paste0("/cauwerx/gwas/05_gwas/04_gwas/duplication_only/data/", sex, "/significant/00_significant_dup_", sex, ".txt")))
sig_probes <- sig_probes[, c(17, 1:3, 15)]
colnames(sig_probes)[2] <-  "CHR"



#################################################
### STEP 2: Prune ###############################

# Unique combinations of disease - chromosome pairs
unique_combo <- as.data.frame(sig_probes %>% count(PHENO, CHR))
colnames(unique_combo)[3] <- "TOTAL"

# Parameters
window <- 3000
step <- 500
r2 <- 0.8

# Empty dataframe to store results
summary_pruning <- unique_combo

# Loop over files to prune
for (i in 1:nrow(unique_combo)){

	# Define disease and chromosome & select probes
	p <- unique_combo[i, "PHENO"]
	chr <- unique_combo[i, "CHR"]
	df <- sig_probes[which(sig_probes$PHENO == p & sig_probes$CHR == chr), ]
	print(paste0("Pruning chromosome ", chr, " for ", p, " (", nrow(df), " probe(s))"))

	# Define file names
	result_file <- paste0("/cauwerx/gwas/05_gwas/05_pruning/duplication_only/data/temp/", sex, "/probes_dup_", sex, "_r2_", r2, "_chr", chr, ".", p)
	probe_file <- paste0("/cauwerx/gwas/05_gwas/05_pruning/duplication_only/data/temp/", sex, "/probes/input_probes_dup_", sex, "_chr", chr,".", p, ".txt")
	fake_freq_file <- paste0("/cauwerx/gwas/05_gwas/05_pruning/duplication_only/data/temp/", sex, "/p_value_freq/p_val_freq_dup_", sex, "_chr", chr, ".", p, ".afreq")


	# If there is only one probe, retain and save it for the next step
	if(nrow(df) == 1){

		# Save the probe
		print("Number of remaining after pruning: 1")
		fwrite(df[, "ID", drop = F], paste0(result_file, ".prune.in"), col.names = F, row.names = F, quote = F, sep = "\t")

		# Fill in the summary table
		summary_pruning[i, "PRUNED"] <- 1

		# Go to the next loop iteration
		next
	

	# Else, prune probes with PLINK v2
	}  else {

		# Prepare a probe file
		fwrite(df[, "ID", drop = F], probe_file, row.names = F, col.names = F, sep = "\t", quote = F)

		# Prepare a fake frequency file from the significant Fisher probes to prune in a p-value-aware fashion
		fake_freq <- data.frame(CHR = df$CHR, ID = df$ID, REF = "A", ALT = "T", ALT_FREQS = rescale(-log10(df$P), to = c(0.1, 0.4))) # OBS_CT = df_sig_probes$OBS_CT
		colnames(fake_freq)[1] <- "#CHROM"
		fwrite(fake_freq, fake_freq_file, col.names = T, row.names = F, quote = F, sep = "\t")

		# Run PLINK v2
		input <- paste0("/data/UKBB/cnv_calls/PLINK/duplication_only/ukb_cnv_bed/ukb_cnv_chr", chr) # PLINK file set with duplication encoding; Generation of this file is described in Auwerx et al., 2022
		samples <- paste0("/cauwerx/gwas/01_samples/data/samples_white_british_", sex, ".txt") # File generated by "01_samples/sample_filtering.R"
		system(paste("/cauwerx/softwares/plink2/plink2",
 					"--fam /data/UKBB/cnv_calls/PLINK/mirror/ukb_cnv_bed/ukb_cnv_chrX_onlyF.fam", # Fake .fam file (all individuals = females) to deal with PLINK's male hemizygozity assumption (see Supplemental Note 1)
					 "--bfile", input,
					 "--read-freq", fake_freq_file,
					 "--keep", samples,
					 "--extract", probe_file,
					 "--indep-pairwise", window, step, r2,
					 "--out", result_file))

		# Delete the log file
		unlink(paste0(result_file, ".log"))

		# Assess PLINK run
		print(paste0("Number of remaining after pruning: ", nrow(as.data.frame(fread(paste0(result_file, ".prune.in"), header = F)))))

		# Fill in the summary table
		summary_pruning[i, "PRUNED"] <- nrow(as.data.frame(fread(paste0(result_file, ".prune.in"), header = F)))
	}
} 
rm(i, p, chr, df, input, samples, result_file, probe_file, fake_freq_file)

# Print a summary & save
print(paste("pruning at r2 =",r2," reduced the number of probes from ", sum(summary_pruning$TOTAL), " to ", sum(summary_pruning$PRUNED)))	
fwrite(summary_pruning, paste0("/cauwerx/gwas/05_gwas/05_pruning/duplication_only/data/", sex, "/00_summary_pruning_dup_", sex, ".txt"), row.names = F, col.names = T, quote = F, sep = "\t") 



#################################################
### STEP 3: Extract remaining probes ############

 # Identify unique diseases with at least one probe
unique_p <- unique(unique_combo$PHENO)
print(paste0(length(unique_p)," phenotypes to assess"))

# Create an empty dataframe to store summary of the quality control
summary_qc <- data.frame()

# Loop over remaining diseases and extract association information for these probes
for (up in unique_p){

	# List relevant prune.in files
	prune.in_list <- list.files(path = paste0("/cauwerx/gwas/05_gwas/05_pruning/duplication_only/data/temp/", sex), pattern = paste0("\\.", up, ".prune.in"), full.names = T, recursive = F)

 	# Load and merge relevant prune.in files
	df_probes <- data.frame()
	for (f in prune.in_list) {
		df <- as.data.frame(fread(f, header = F, col.names = "ID"))
		df_probes <- rbind(df_probes, df)	
	}; rm(f, df)
	print(paste0("Retaining ", nrow(df_probes), " probe(s) for ", up))

	# Load relevant GWAS association data; File generated by "05_gwas/04_gwas/duplication_only/02_correct_merge_binary_gwas_dup.R" 
	df_gwas <- as.data.frame(fread(paste0("/cauwerx/gwas/05_gwas/04_gwas/duplication_only/data/", sex, "/significant/gwas_significant_dup_", sex, ".", up, ".txt")))

	# Subset retained probes
	df_gwas_probes <- df_gwas[df_gwas$ID %in% df_probes$ID, ]
	if (nrow(df_probes) != nrow(df_gwas_probes)){print("Warning! Number of retained probes does not match.")} 

	# Save retained probes/phenotype for the SCA
	fwrite(data.frame(ID = df_gwas_probes$ID), paste0("/cauwerx/gwas/05_gwas/05_pruning/duplication_only/data/", sex, "/SCA_probes/qc_probes_dup_", sex, ".", up, ".txt"), col.names = F, row.names = F, quote = F, sep = "\t")

	# Add results to the main summary QC file
	df_gwas_probes$PHENO <- up
	summary_qc <- rbind(summary_qc, df_gwas_probes)

}
rm(up, df_probes, prune.in_list, df_gwas, df_gwas_probes)



#################################################
### Save input for SCA ##########################

# Save GWAS summary statistics for the stepwise conditional analysis (first round) 
fwrite(summary_qc, paste0("/cauwerx/gwas/05_gwas/05_pruning/duplication_only/data/", sex, "/00_qc_probes_gwas_dup_", sex, ".txt"), col.names = T, row.names = F, quote = F, sep = "\t")
