# Summarize results from the filtering (CNV frequency > 0.01%) and pruning (r 0.9999)

#################################################
### Libraries ###################################
library(data.table)
library(dplyr)
library(tidyr)
library(stringr)



#################################################
### Summarize results from different chromosomes

# Define the pruning threshold
thr_r <- 0.9999

# List files generated by "02_probes/01_freq_prune.R"
prune_list <- list.files("/cauwerx/gwas/02_probes/data/pruning", pattern = "prune.in", full.names = T, recursive = F)
print(paste0("Number of files for r ", thr_r, ": ", length(prune_list)))

# Loop over these files and compute the number of retained probes after pruning
counter <- 0
for (f in prune_list) {
	chr <- sub(".prune.in", "", sub(".*chr", "", f))
	probes <- nrow(as.data.frame(fread(f, header = F)))
	print(paste0("Number of probes retained at r ", thr_r, " on chromosome ", chr, ": ", probes))
	counter <- counter + probes
}

print(paste0("TOTAL: ", counter))
