# Correct the OR, merge files by disease, select significant associations. Configuration: duplication-only.

#################################################
### Libraries & External arguments ##############
library(data.table)
library(dplyr)
library(tibble)
library(gtools)

# Arguments
args <- commandArgs(trailingOnly = T)
sex <- args[1]
print(paste0("Analyzing: ", sex))

# Filter for probe selection
thr <- 0.05/6633 # = 7.5e-6



#################################################
### STEP 1: Correct ORs #########################

# List all files to correct; Generated by "05_gwas/04_gwas/01_binary_gwas_dup_*.sh"
files_to_correct <- list.files(paste0("/cauwerx/gwas/05_gwas/04_gwas/duplication_only/data/temp/", sex), pattern = "*.glm.*", recursive = F, full.names = T)
print(paste0("Number of files to analyze: ", length(files_to_correct)))

# Loop over files to correct
for (f in files_to_correct) {

	# Load file
	df <- as.data.frame(fread(f, header = T))

	#### Continuous trait (DiseaseBurden) ####
	if (grepl("DiseaseBurden", f))  {

		# Make relevant columns numeric
		df[9:14] <- lapply(df[9:14], as.numeric)

		# Correct associations where A1 = "A"; Correct Beta, CI, Z, alleles 
		df[which(df$A1 == "A"), c(9, 11, 12, 13)] <- -1 * df[which(df$A1 == "A"), c(9, 11, 12, 13)]
		df[which(df$A1 == "A"), "REF"] <- "A"
		df[which(df$A1 == "A"), "ALT"] <- "T"
		df[which(df$A1 == "A"), "A1"] <- "T"
		colnames(df)[c(11,12)] <- c("U95", "L95")
		df <- df[, c(1:10, 12, 11, 13:15)]

	#### Binary traits (others) ##############
	} else {

		# Make relevant columns numeric
		df[10:15] <- lapply(df[10:15], as.numeric)

		# Correct associations where A1 = "A"; Correct: OR, CI, Z, alleles; Not correct: SE(ln(OR)), P
		df[df$A1 == "A", "OR"] <- exp(-log(df[df$A1 == "A", "OR"]))
		df[df$A1 == "A", "L95"] <- exp(log(df[df$A1 == "A", "OR"]) - 1.96*df[df$A1 == "A", "LOG(OR)_SE"]) 
		df[df$A1 == "A", "U95"] <- exp(log(df[df$A1 == "A", "OR"]) + 1.96*df[df$A1 == "A", "LOG(OR)_SE"]) 
		df[df$A1 == "A", "Z_STAT"] <- log(df[df$A1 == "A", "OR"])/df[df$A1 == "A", "LOG(OR)_SE"]
		df[df$A1 == "A", "REF"] <- "A"
		df[df$A1 == "A", "ALT"] <- "T"
		df[df$A1 == "A", "A1"] <- "T"
	}

	# Save
	fwrite(df, f, col.names = T, row.names = F, sep = "\t", quote = F)

}



#################################################
### STEP 2: Merge by disease ####################

# List unique diseases; Header of the file generated by "04_phenotypes/01_ICD10_extraction.R"
all_pheno <- c(names(as.data.frame(fread(paste0("/cauwerx/gwas/04_phenotypes/data/pheno_ICD10_", sex,".txt"), nrow = 0)))[-1])

# Create an empty dataframe to store results
significant_associations <- data.frame() 

# Loop over diseases
for (p in all_pheno) {

	# Define the disease
	print(paste0("Analyzing: ", p, " (duplication-only, ", sex,")"))

	# List files corresponding to the defined phenotype; Generated by "05_gwas/04_gwas/01_binary_gwas_dup_*.sh"
	files_p <- mixedsort(list.files(paste0("/cauwerx/gwas/05_gwas/04_gwas/duplication_only/data/temp/", sex), pattern = paste0("*\\.", p, ".glm"), recursive = F, full.names = T))
	print(paste0("Number of files to merge: ", length(files_p)))

	# Merge all listed files
	df <- data.frame()
	for (fp in files_p) {
		df_temp <- as.data.frame(fread(fp, header = T))
		df <- rbind(df, df_temp)
	}

	# If DiseaseBurden, add an additional column for compatibility
	if(p == "DiseaseBurden") {
		df <- add_column(df, `FIRTH?` = NA, .before = "TEST")
		colnames(df)[c(10,11,14)] <- c("OR", "LOG(OR)_SE", "Z_STAT")}

	# Save
	fwrite(df, paste0("/cauwerx/gwas/05_gwas/04_gwas/duplication_only/data/", sex,"/gwas_dup_", sex,".", p, ".txt"), col.names = T, row.names = F, sep = "\t", quote = F)

	# Retain significant files & save
	sig_df <- df[df$P <= thr & !is.na(df$P), ]
	print(paste0("Number of significant associations: ", nrow(sig_df)))
	if (nrow(sig_df) > 0) {
		fwrite(sig_df, paste0("/cauwerx/gwas/05_gwas/04_gwas/duplication_only/data/", sex,"/significant/gwas_significant_dup_", sex,".", p, ".txt"), col.names = T, row.names = F, sep = "\t", quote = F)}

	# If there is at least one significant association, combine with global dataframe
	if (nrow(sig_df) > 0) {
		sig_df$PHENO <- p
		significant_associations <- rbind(significant_associations, sig_df)}
	
}



#################################################
### Save significant associations ###############

# Order and save
significant_associations <- significant_associations[mixedorder(significant_associations$`#CHROM`, significant_associations$POS, significant_associations$PHENO, decreasing = F), ]
fwrite(significant_associations, paste0("/cauwerx/gwas/05_gwas/04_gwas/duplication_only/data/", sex,"/significant/00_significant_dup_", sex,".txt"), col.names = T, row.names = F, sep = "\t", quote = F)
