# Annotate combined CNVR with ENSEMBL & HGNC gene symbols using ANNOVAR.

#################################################
### Libraries ###################################
library(data.table)
library(dplyr)



#################################################
### STEP 1: Load CNVRs ##########################

# All merged associations; File generated by "07_CNVR/combined/01_combine_models.R"
cnvrs <- as.data.frame(fread("/cauwerx/gwas/07_CNVR/combined/data/combined_CNVR/all_combined_CNVR.txt",  header = F, select = c(1, 3, 5, 7:9, 11), col.names =  c("PHENO", "CHR", "OR", "P", "START", "END", "ALL_MODELS")))
print(paste0("Number of CNVRs to annotate: ", nrow(cnvrs)))



#################################################
### STEP 2: ANNOVAR input file ##################

# Remodel
cnvrs <- data.table(CHR = cnvrs$CHR, START = cnvrs$START, END = cnvrs$END,
					REF = 0, OBS = "-",
					PHENO = cnvrs$PHENO, OR = cnvrs$OR, P = cnvrs$P, ALL_MODELS = cnvrs$ALL_MODELS)

# Save
annovar_input <- "/cauwerx/gwas/08_ANNOVAR/combined/data/temp/gene_annotation/ANNOVAR_input_CNVRs.txt"
fwrite(cnvrs, annovar_input, col.names = F, row.names = F, quote = F, sep = "\t")



#################################################
### STEP 3: ANNOVAR annotation ##################

# Run ANNOVAR in terminal - ENSEMBL
output_ENSEMBL <- "/cauwerx/gwas/08_ANNOVAR/combined/data/gene_annotation/CNVR_ANNOVAR_ENSEMBL"
system(paste("/cauwerx/softwares/ANNOVAR-20191024/annotate_variation.pl",
			 "--geneanno -dbtype ensGene",
			 "-out", output_ENSEMBL, 
		     "-build hg19", 
			 annovar_input,
			 "/cauwerx/softwares/ANNOVAR-20191024/humandb/"))	
unlink(paste0(output_ENSEMBL, ".log"))

# Run ANNOVAR in terminal - HGNC
output_HGNC <- "/cauwerx/gwas/08_ANNOVAR/combined/data/gene_annotation/CNVR_ANNOVAR_HGNC"
system(paste("/cauwerx/softwares/ANNOVAR-20191024/annotate_variation.pl",
			 "--geneanno -dbtype refGene",
			 "-out", output_HGNC, 
		     "-build hg19", 
			 annovar_input,
			 "/cauwerx/softwares/ANNOVAR-20191024/humandb/"))
unlink(paste0(output_HGNC, ".log"))
